name: Build packages

on:
  push:
    branches: [ master, workflow ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Tailscale build container
      run: make build-tailscaled-container

    - name: Build Tailscale binaries
      run: make out/tailscaled

    - name: Create QDK build container
      run: make build-qdk-container

    - name: Create Tailscale QPKG
      run : make out/pkg

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: qpkg
        path: out/pkg/
