name: Build packages

on:
  push:
    branches: [ master, workflow ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Create Tailscale build container
      run: make build-tailscaled-container

    - name: Build Tailscale binaries
      run: make out/tailscaled

    - name: Create QDK build container
      run: make build-qdk-container

    - name: Create Tailscale QPKG
      run : make out/pkg
